platform :ios, '8.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'AFNetworking', '~> 2.6.3'
pod 'JSONModel', '~> 1.1.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'MJRefresh', '~> 3.0.7'
pod 'FMDB', '~> 2.5'
pod 'Masonry', '~> 0.6.3'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.2'
pod 'AMap2DMap', '~> 3.2.0'
pod 'AMapSearch', '~> 3.1.0'
pod 'AMapLocation', '~> 1.0.1'
